//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Addresseditpanel_prefab
    {
        public const string BundleName = "addresseditpanel_prefab";
        public const string ADDRESSEDITPANEL = "addresseditpanel";
    }
    public class Addresslistpanel_prefab
    {
        public const string BundleName = "addresslistpanel_prefab";
        public const string ADDRESSLISTPANEL = "addresslistpanel";
    }
    public class Addresspickerpanel_prefab
    {
        public const string BundleName = "addresspickerpanel_prefab";
        public const string ADDRESSPICKERPANEL = "addresspickerpanel";
    }
    public class Attendance_main_add_png
    {
        public const string BundleName = "attendance_main_add_png";
        public const string ATTENDANCE_MAIN_ADD = "attendance_main_add";
    }
    public class Attendanceaddpanel_prefab
    {
        public const string BundleName = "attendanceaddpanel_prefab";
        public const string ATTENDANCEADDPANEL = "attendanceaddpanel";
    }
    public class Attendanceaudiorecordpanel_prefab
    {
        public const string BundleName = "attendanceaudiorecordpanel_prefab";
        public const string ATTENDANCEAUDIORECORDPANEL = "attendanceaudiorecordpanel";
    }
    public class Attendanceinstructionspanel_prefab
    {
        public const string BundleName = "attendanceinstructionspanel_prefab";
        public const string ATTENDANCEINSTRUCTIONSPANEL = "attendanceinstructionspanel";
    }
    public class Attendancemainpanel_prefab
    {
        public const string BundleName = "attendancemainpanel_prefab";
        public const string ATTENDANCEMAINPANEL = "attendancemainpanel";
    }
    public class Attendancerulepanel_prefab
    {
        public const string BundleName = "attendancerulepanel_prefab";
        public const string ATTENDANCERULEPANEL = "attendancerulepanel";
    }
    public class Attendanceselectpanel_prefab
    {
        public const string BundleName = "attendanceselectpanel_prefab";
        public const string ATTENDANCESELECTPANEL = "attendanceselectpanel";
    }
    public class Attendancesharepanel_prefab
    {
        public const string BundleName = "attendancesharepanel_prefab";
        public const string ATTENDANCESHAREPANEL = "attendancesharepanel";
    }
    public class Audio_pause_record_png
    {
        public const string BundleName = "audio_pause_record_png";
        public const string AUDIO_PAUSE_RECORD = "audio_pause_record";
    }
    public class Audio_record_png
    {
        public const string BundleName = "audio_record_png";
        public const string AUDIO_RECORD = "audio_record";
    }
    public class Audio_recording_png
    {
        public const string BundleName = "audio_recording_png";
        public const string AUDIO_RECORDING = "audio_recording";
    }
    public class Audioclips
    {
        public const string BundleName = "audioclips";
        public const string MAIN_BG_MUSIC = "main_bg_music";
    }
    public class Babyinfopanel_prefab
    {
        public const string BundleName = "babyinfopanel_prefab";
        public const string BABYINFOPANEL = "babyinfopanel";
    }
    public class Bg_audio_png
    {
        public const string BundleName = "bg_audio_png";
        public const string BG_AUDIO = "bg_audio";
    }
    public class Bg_audoi_bottom_png
    {
        public const string BundleName = "bg_audoi_bottom_png";
        public const string BG_AUDOI_BOTTOM = "bg_audoi_bottom";
    }
    public class Bg_book_png
    {
        public const string BundleName = "bg_book_png";
        public const string BG_BOOK = "bg_book";
    }
    public class Bg_btn_png
    {
        public const string BundleName = "bg_btn_png";
        public const string BG_BTN = "bg_btn";
    }
    public class Bg_detail_title_png
    {
        public const string BundleName = "bg_detail_title_png";
        public const string BG_DETAIL_TITLE = "bg_detail_title";
    }
    public class Bg_en_png
    {
        public const string BundleName = "bg_en_png";
        public const string BG_EN = "bg_en";
    }
    public class Bg_item_audio_png
    {
        public const string BundleName = "bg_item_audio_png";
        public const string BG_ITEM_AUDIO = "bg_item_audio";
    }
    public class Bg_item_floor_png
    {
        public const string BundleName = "bg_item_floor_png";
        public const string BG_ITEM_FLOOR = "bg_item_floor";
    }
    public class Bg_item_video_png
    {
        public const string BundleName = "bg_item_video_png";
        public const string BG_ITEM_VIDEO = "bg_item_video";
    }
    public class Bg_pic_book_bottom_png
    {
        public const string BundleName = "bg_pic_book_bottom_png";
        public const string BG_PIC_BOOK_BOTTOM = "bg_pic_book_bottom";
    }
    public class Bg_pic_book_png
    {
        public const string BundleName = "bg_pic_book_png";
        public const string BG_PIC_BOOK = "bg_pic_book";
    }
    public class Bg_pic_png
    {
        public const string BundleName = "bg_pic_png";
        public const string BG_PIC = "bg_pic";
    }
    public class Bg_png
    {
        public const string BundleName = "bg_png";
        public const string BG = "bg";
    }
    public class Bg_rect_png
    {
        public const string BundleName = "bg_rect_png";
        public const string BG_RECT = "bg_rect";
    }
    public class Bg_sex_nor_png
    {
        public const string BundleName = "bg_sex_nor_png";
        public const string BG_SEX_NOR = "bg_sex_nor";
    }
    public class Bg_sex_sel_png
    {
        public const string BundleName = "bg_sex_sel_png";
        public const string BG_SEX_SEL = "bg_sex_sel";
    }
    public class Bg_small_rect_png
    {
        public const string BundleName = "bg_small_rect_png";
        public const string BG_SMALL_RECT = "bg_small_rect";
    }
    public class Bg_xxqg_png
    {
        public const string BundleName = "bg_xxqg_png";
        public const string BG_XXQG = "bg_xxqg";
    }
    public class Bindcheckwifipanel_prefab
    {
        public const string BundleName = "bindcheckwifipanel_prefab";
        public const string BINDCHECKWIFIPANEL = "bindcheckwifipanel";
    }
    public class Bindconfirmbootpanel_prefab
    {
        public const string BundleName = "bindconfirmbootpanel_prefab";
        public const string BINDCONFIRMBOOTPANEL = "bindconfirmbootpanel";
    }
    public class Binddevicepanel_prefab
    {
        public const string BundleName = "binddevicepanel_prefab";
        public const string BINDDEVICEPANEL = "binddevicepanel";
    }
    public class Bindguidepanel_prefab
    {
        public const string BundleName = "bindguidepanel_prefab";
        public const string BINDGUIDEPANEL = "bindguidepanel";
    }
    public class Bindwifimessagepanel_prefab
    {
        public const string BundleName = "bindwifimessagepanel_prefab";
        public const string BINDWIFIMESSAGEPANEL = "bindwifimessagepanel";
    }
    public class Bookdaylist
    {
        public const string BundleName = "bookdaylist";
        public const string BG_BUTTON = "bg_button";
        public const string BG_DAY_ITEM = "bg_day_item";
        public const string BG_SMALL_RECT = "bg_small_rect";
        public const string BG_TITLE = "bg_title";
        public const string IC_ARROW_DOWN = "ic_arrow_down";
        public const string IC_DAY_ITEM = "ic_day_item";
        public const string IC_LOCK = "ic_lock";
        public const string IC_MUSIC = "ic_music";
        public const string IC_PIC_BOOK = "ic_pic_book";
        public const string IC_TARGET = "ic_target";
        public const string IC_VIDEO = "ic_video";
        public const string IMG_PUNCH = "img_punch";
        public const string IMG_REST = "img_rest";
    }
    public class Bookdaylistpanel_prefab
    {
        public const string BundleName = "bookdaylistpanel_prefab";
        public const string BOOKDAYLISTPANEL = "bookdaylistpanel";
    }
    public class Bookdaypanel_prefab
    {
        public const string BundleName = "bookdaypanel_prefab";
        public const string BOOKDAYPANEL = "bookdaypanel";
    }
    public class Bookdetailpanel_prefab
    {
        public const string BundleName = "bookdetailpanel_prefab";
        public const string BOOKDETAILPANEL = "bookdetailpanel";
    }
    public class Bookmonth
    {
        public const string BundleName = "bookmonth";
        public const string BG_MONTH = "bg_month";
        public const string IC_ROPE = "ic_rope";
    }
    public class Btn_add_photo_png
    {
        public const string BundleName = "btn_add_photo_png";
        public const string BTN_ADD_PHOTO = "btn_add_photo";
    }
    public class Btn_attendance_nor_png
    {
        public const string BundleName = "btn_attendance_nor_png";
        public const string BTN_ATTENDANCE_NOR = "btn_attendance_nor";
    }
    public class Btn_attendance_sel_png
    {
        public const string BundleName = "btn_attendance_sel_png";
        public const string BTN_ATTENDANCE_SEL = "btn_attendance_sel";
    }
    public class Btn_back_png
    {
        public const string BundleName = "btn_back_png";
        public const string BTN_BACK = "btn_back";
    }
    public class Btn_code_nor_png
    {
        public const string BundleName = "btn_code_nor_png";
        public const string BTN_CODE_NOR = "btn_code_nor";
    }
    public class Btn_code_sel_png
    {
        public const string BundleName = "btn_code_sel_png";
        public const string BTN_CODE_SEL = "btn_code_sel";
    }
    public class Btn_hide_pwd_png
    {
        public const string BundleName = "btn_hide_pwd_png";
        public const string BTN_HIDE_PWD = "btn_hide_pwd";
    }
    public class Btn_show_pwd_png
    {
        public const string BundleName = "btn_show_pwd_png";
        public const string BTN_SHOW_PWD = "btn_show_pwd";
    }
    public class Button_audio_mp3
    {
        public const string BundleName = "button_audio_mp3";
        public const string BUTTON_AUDIO = "button_audio";
    }
    public class Choosephotopanel_prefab
    {
        public const string BundleName = "choosephotopanel_prefab";
        public const string CHOOSEPHOTOPANEL = "choosephotopanel";
    }
    public class Cn_bg_music_mp3
    {
        public const string BundleName = "cn_bg_music_mp3";
        public const string CN_BG_MUSIC = "cn_bg_music";
    }
    public class Cn_nodata_png
    {
        public const string BundleName = "cn_nodata_png";
        public const string CN_NODATA = "cn_nodata";
    }
    public class Collectgiftboxpanel_prefab
    {
        public const string BundleName = "collectgiftboxpanel_prefab";
        public const string COLLECTGIFTBOXPANEL = "collectgiftboxpanel";
    }
    public class Connectdevicepanel_prefab
    {
        public const string BundleName = "connectdevicepanel_prefab";
        public const string CONNECTDEVICEPANEL = "connectdevicepanel";
    }
    public class Cover_bg_png
    {
        public const string BundleName = "cover_bg_png";
        public const string COVER_BG = "cover_bg";
    }
    public class Cover_corner_png
    {
        public const string BundleName = "cover_corner_png";
        public const string COVER_CORNER = "cover_corner";
    }
    public class Createorderpanel_prefab
    {
        public const string BundleName = "createorderpanel_prefab";
        public const string CREATEORDERPANEL = "createorderpanel";
    }
    public class Dailytaskpanel_prefab
    {
        public const string BundleName = "dailytaskpanel_prefab";
        public const string DAILYTASKPANEL = "dailytaskpanel";
    }
    public class Datepickerpanel_prefab
    {
        public const string BundleName = "datepickerpanel_prefab";
        public const string DATEPICKERPANEL = "datepickerpanel";
    }
    public class Devicestatuspanel_prefab
    {
        public const string BundleName = "devicestatuspanel_prefab";
        public const string DEVICESTATUSPANEL = "devicestatuspanel";
    }
    public class Dinoprefab_prefab
    {
        public const string BundleName = "dinoprefab_prefab";
        public const string DINOPREFAB = "dinoprefab";
    }
    public class Dinosaur_en_mp3
    {
        public const string BundleName = "dinosaur_en_mp3";
        public const string DINOSAUR_EN = "dinosaur_en";
    }
    public class En_bg_music_mp3
    {
        public const string BundleName = "en_bg_music_mp3";
        public const string EN_BG_MUSIC = "en_bg_music";
    }
    public class En_nodata_png
    {
        public const string BundleName = "en_nodata_png";
        public const string EN_NODATA = "en_nodata";
    }
    public class Familyaddpanel_prefab
    {
        public const string BundleName = "familyaddpanel_prefab";
        public const string FAMILYADDPANEL = "familyaddpanel";
    }
    public class Familysettingpanel_prefab
    {
        public const string BundleName = "familysettingpanel_prefab";
        public const string FAMILYSETTINGPANEL = "familysettingpanel";
    }
    public class Giftlistpanel_prefab
    {
        public const string BundleName = "giftlistpanel_prefab";
        public const string GIFTLISTPANEL = "giftlistpanel";
    }
    public class Historicalphotowallpanel_prefab
    {
        public const string BundleName = "historicalphotowallpanel_prefab";
        public const string HISTORICALPHOTOWALLPANEL = "historicalphotowallpanel";
    }
    public class Ic_audiio_pause_png
    {
        public const string BundleName = "ic_audiio_pause_png";
        public const string IC_AUDIIO_PAUSE = "ic_audiio_pause";
    }
    public class Ic_audio_playing_png
    {
        public const string BundleName = "ic_audio_playing_png";
        public const string IC_AUDIO_PLAYING = "ic_audio_playing";
    }
    public class Ic_audio_png
    {
        public const string BundleName = "ic_audio_png";
        public const string IC_AUDIO = "ic_audio";
    }
    public class Ic_audio_toggle_png
    {
        public const string BundleName = "ic_audio_toggle_png";
        public const string IC_AUDIO_TOGGLE = "ic_audio_toggle";
    }
    public class Ic_baby_boy_png
    {
        public const string BundleName = "ic_baby_boy_png";
        public const string IC_BABY_BOY = "ic_baby_boy";
    }
    public class Ic_baby_girl_png
    {
        public const string BundleName = "ic_baby_girl_png";
        public const string IC_BABY_GIRL = "ic_baby_girl";
    }
    public class Ic_binddetermine_png
    {
        public const string BundleName = "ic_binddetermine_png";
        public const string IC_BINDDETERMINE = "ic_binddetermine";
    }
    public class Ic_book_item_bg_png
    {
        public const string BundleName = "ic_book_item_bg_png";
        public const string IC_BOOK_ITEM_BG = "ic_book_item_bg";
    }
    public class Ic_clip_png
    {
        public const string BundleName = "ic_clip_png";
        public const string IC_CLIP = "ic_clip";
    }
    public class Ic_close_png
    {
        public const string BundleName = "ic_close_png";
        public const string IC_CLOSE = "ic_close";
    }
    public class Ic_dailyclocksbtn_png
    {
        public const string BundleName = "ic_dailyclocksbtn_png";
        public const string IC_DAILYCLOCKSBTN = "ic_dailyclocksbtn";
    }
    public class Ic_dailyitemdontreceive_png
    {
        public const string BundleName = "ic_dailyitemdontreceive_png";
        public const string IC_DAILYITEMDONTRECEIVE = "ic_dailyitemdontreceive";
    }
    public class Ic_dailyitemgoldsharesel_png
    {
        public const string BundleName = "ic_dailyitemgoldsharesel_png";
        public const string IC_DAILYITEMGOLDSHARESEL = "ic_dailyitemgoldsharesel";
    }
    public class Ic_dailyitemreceive_png
    {
        public const string BundleName = "ic_dailyitemreceive_png";
        public const string IC_DAILYITEMRE = "ic_dailyitemre";
        public const string IC_DAILYITEMRECEIVE = "ic_dailyitemreceive";
    }
    public class Ic_dailyitemunreceive_png
    {
        public const string BundleName = "ic_dailyitemunreceive_png";
        public const string IC_DAILYITEMUNRECEIVE = "ic_dailyitemunreceive";
    }
    public class Ic_dailyshare_png
    {
        public const string BundleName = "ic_dailyshare_png";
        public const string IC_DAILYSHARE = "ic_dailyshare";
    }
    public class Ic_dailysharesel_png
    {
        public const string BundleName = "ic_dailysharesel_png";
        public const string IC_DAILYSHARESEL = "ic_dailysharesel";
    }
    public class Ic_dailytask_png
    {
        public const string BundleName = "ic_dailytask_png";
        public const string IC_DAILYTASK = "ic_dailytask";
    }
    public class Ic_dailytasksel_png
    {
        public const string BundleName = "ic_dailytasksel_png";
        public const string IC_DAILYTASKSEL = "ic_dailytasksel";
    }
    public class Ic_devicebatteryhigh_png
    {
        public const string BundleName = "ic_devicebatteryhigh_png";
        public const string IC_DEVICEBATTERYHIGH = "ic_devicebatteryhigh";
    }
    public class Ic_devicebatterylow_png
    {
        public const string BundleName = "ic_devicebatterylow_png";
        public const string IC_DEVICEBATTERYLOW = "ic_devicebatterylow";
    }
    public class Ic_devicebatterymid_png
    {
        public const string BundleName = "ic_devicebatterymid_png";
        public const string IC_DEVICEBATTERYMID = "ic_devicebatterymid";
    }
    public class Ic_devicewificonnect_png
    {
        public const string BundleName = "ic_devicewificonnect_png";
        public const string IC_DEVICEWIFICONNECT = "ic_devicewificonnect";
    }
    public class Ic_devicewifiunconnect_png
    {
        public const string BundleName = "ic_devicewifiunconnect_png";
        public const string IC_DEVICEWIFIUNCONNECT = "ic_devicewifiunconnect";
    }
    public class Ic_head_boy_png
    {
        public const string BundleName = "ic_head_boy_png";
        public const string IC_HEAD_BOY = "ic_head_boy";
    }
    public class Ic_head_brother_png
    {
        public const string BundleName = "ic_head_brother_png";
        public const string IC_HEAD_BROTHER = "ic_head_brother";
    }
    public class Ic_head_father_png
    {
        public const string BundleName = "ic_head_father_png";
        public const string IC_HEAD_FATHER = "ic_head_father";
    }
    public class Ic_head_girl_png
    {
        public const string BundleName = "ic_head_girl_png";
        public const string IC_HEAD_GIRL = "ic_head_girl";
    }
    public class Ic_head_grand_father_png
    {
        public const string BundleName = "ic_head_grand_father_png";
        public const string IC_HEAD_GRAND_FATHER = "ic_head_grand_father";
    }
    public class Ic_head_grand_mother_png
    {
        public const string BundleName = "ic_head_grand_mother_png";
        public const string IC_HEAD_GRAND_MOTHER = "ic_head_grand_mother";
    }
    public class Ic_head_mother_png
    {
        public const string BundleName = "ic_head_mother_png";
        public const string IC_HEAD_MOTHER = "ic_head_mother";
    }
    public class Ic_head_sister_png
    {
        public const string BundleName = "ic_head_sister_png";
        public const string IC_HEAD_SISTER = "ic_head_sister";
    }
    public class Ic_learn_read_png
    {
        public const string BundleName = "ic_learn_read_png";
        public const string IC_LEARN_READ = "ic_learn_read";
    }
    public class Ic_listen_idiom_png
    {
        public const string BundleName = "ic_listen_idiom_png";
        public const string IC_LISTEN_IDIOM = "ic_listen_idiom";
    }
    public class Ic_listen_music_png
    {
        public const string BundleName = "ic_listen_music_png";
        public const string IC_LISTEN_MUSIC = "ic_listen_music";
    }
    public class Ic_listen_story_png
    {
        public const string BundleName = "ic_listen_story_png";
        public const string IC_LISTEN_STORY = "ic_listen_story";
    }
    public class Ic_lock_png
    {
        public const string BundleName = "ic_lock_png";
        public const string IC_LOCK = "ic_lock";
    }
    public class Ic_orange_png
    {
        public const string BundleName = "ic_orange_png";
        public const string IC_ORANGE = "ic_orange";
    }
    public class Ic_pic_book_png
    {
        public const string BundleName = "ic_pic_book_png";
        public const string IC_WORD_CARD = "ic_word_card";
        public const string BG_PIC_BOOK = "bg_pic_book";
    }
    public class Ic_picbook_png
    {
        public const string BundleName = "ic_picbook_png";
        public const string IC_PICBOOK = "ic_picbook";
    }
    public class Ic_play_game_png
    {
        public const string BundleName = "ic_play_game_png";
        public const string IC_PLAY_GAME = "ic_play_game";
    }
    public class Ic_read_book_png
    {
        public const string BundleName = "ic_read_book_png";
        public const string IC_READ_BOOK = "ic_read_book";
    }
    public class Ic_rect_png
    {
        public const string BundleName = "ic_rect_png";
        public const string IC_RECT = "ic_rect";
    }
    public class Ic_rect_title_png
    {
        public const string BundleName = "ic_rect_title_png";
        public const string IC_RECT_TITLE = "ic_rect_title";
    }
    public class Ic_savepwd_png
    {
        public const string BundleName = "ic_savepwd_png";
        public const string IC_SAVEPWD = "ic_savepwd";
    }
    public class Ic_share_audio_png
    {
        public const string BundleName = "ic_share_audio_png";
        public const string IC_SHARE_AUDIO = "ic_share_audio";
    }
    public class Ic_share_chinese_png
    {
        public const string BundleName = "ic_share_chinese_png";
        public const string IC_SHARE_CHINESE = "ic_share_chinese";
    }
    public class Ic_share_english_png
    {
        public const string BundleName = "ic_share_english_png";
        public const string IC_SHARE_ENGLISH = "ic_share_english";
    }
    public class Ic_share_qiangguo_png
    {
        public const string BundleName = "ic_share_qiangguo_png";
        public const string IC_SHARE_QIANGGUO = "ic_share_qiangguo";
    }
    public class Ic_share_video_png
    {
        public const string BundleName = "ic_share_video_png";
        public const string IC_SHARE_VIDEO = "ic_share_video";
    }
    public class Ic_unsavepwd_png
    {
        public const string BundleName = "ic_unsavepwd_png";
        public const string IC_UNSAVEPWD = "ic_unsavepwd";
    }
    public class Ic_video_png
    {
        public const string BundleName = "ic_video_png";
        public const string IC_VIDEO = "ic_video";
    }
    public class Ic_watch_tv_png
    {
        public const string BundleName = "ic_watch_tv_png";
        public const string IC_WATCH_TV = "ic_watch_tv";
    }
    public class Ic_works_wall_audio_pause_png
    {
        public const string BundleName = "ic_works_wall_audio_pause_png";
        public const string IC_WORKS_WALL_AUDIO_PAUSE = "ic_works_wall_audio_pause";
    }
    public class Ic_works_wall_audio_start_png
    {
        public const string BundleName = "ic_works_wall_audio_start_png";
        public const string IC_WORKS_WALL_AUDIO_START = "ic_works_wall_audio_start";
    }
    public class Integraldescrippanel_prefab
    {
        public const string BundleName = "integraldescrippanel_prefab";
        public const string INTEGRALDESCRIPPANEL = "integraldescrippanel";
    }
    public class Integraldetailpanel_prefab
    {
        public const string BundleName = "integraldetailpanel_prefab";
        public const string INTEGRALDETAILPANEL = "integraldetailpanel";
    }
    public class Item_mask_png
    {
        public const string BundleName = "item_mask_png";
        public const string ITEM_MASK = "item_mask";
    }
    public class Itemaudio_prefab
    {
        public const string BundleName = "itemaudio_prefab";
        public const string ITEMAUDIO = "itemaudio";
    }
    public class Itemcanvas_prefab
    {
        public const string BundleName = "itemcanvas_prefab";
        public const string ITEMCANVAS = "itemcanvas";
    }
    public class Itemcanvaslist_prefab
    {
        public const string BundleName = "itemcanvaslist_prefab";
        public const string ITEMCANVASLIST = "itemcanvaslist";
    }
    public class Itemdailymedalpanel_prefab
    {
        public const string BundleName = "itemdailymedalpanel_prefab";
        public const string ITEMDAILYMEDALPANEL = "itemdailymedalpanel";
    }
    public class Itemexchangelistpanel_prefab
    {
        public const string BundleName = "itemexchangelistpanel_prefab";
        public const string ITEMEXCHANGELISTPANEL = "itemexchangelistpanel";
    }
    public class Itemfamily_prefab
    {
        public const string BundleName = "itemfamily_prefab";
        public const string ITEMFAMILY = "itemfamily";
    }
    public class Itemfamilyprefab_prefab
    {
        public const string BundleName = "itemfamilyprefab_prefab";
        public const string ITEMINFOFAMILYPREFAB = "iteminfofamilyprefab";
    }
    public class Itemgiftlistpanel_prefab
    {
        public const string BundleName = "itemgiftlistpanel_prefab";
        public const string ITEMGIFTLISTPANEL = "itemgiftlistpanel";
    }
    public class Itemhistoryphotowallpanel_prefab
    {
        public const string BundleName = "itemhistoryphotowallpanel_prefab";
        public const string ITEMHISTORYPHOTOWALLPANEL = "itemhistoryphotowallpanel";
    }
    public class Iteminfofamilysettingprefab_prefab
    {
        public const string BundleName = "iteminfofamilysettingprefab_prefab";
        public const string ITEMINFOFAMILYSETTINGPREFAB = "iteminfofamilysettingprefab";
    }
    public class Iteminfouserprefab_prefab
    {
        public const string BundleName = "iteminfouserprefab_prefab";
        public const string ITEMINFOBABYPREFAB = "iteminfobabyprefab";
        public const string ITEMINFOFAMILYEMPTYPREFAB = "iteminfofamilyemptyprefab";
        public const string ITEMINFOFAMILYTITLEPREFAB = "iteminfofamilytitleprefab";
        public const string ITEMINFOUSERPREFAB = "iteminfouserprefab";
    }
    public class Itemintegralgetlistpanel_prefab
    {
        public const string BundleName = "itemintegralgetlistpanel_prefab";
        public const string ITEMINTEGRALGETLISTPANEL = "itemintegralgetlistpanel";
    }
    public class Itemintegralpanel_prefab
    {
        public const string BundleName = "itemintegralpanel_prefab";
        public const string ITEMINTEGRALPANEL = "itemintegralpanel";
    }
    public class Itempicbook_prefab
    {
        public const string BundleName = "itempicbook_prefab";
        public const string ITEMPICBOOK = "itempicbook";
    }
    public class Itempicbookgroup_prefab
    {
        public const string BundleName = "itempicbookgroup_prefab";
        public const string ITEMPICBOOKGROUP = "itempicbookgroup";
    }
    public class Itemtypeaction_prefab
    {
        public const string BundleName = "itemtypeaction_prefab";
        public const string ITEMTYPEACTION = "itemtypeaction";
    }
    public class Itemvideo_prefab
    {
        public const string BundleName = "itemvideo_prefab";
        public const string ITEMVIDEO = "itemvideo";
    }
    public class Lionprefab_prefab
    {
        public const string BundleName = "lionprefab_prefab";
        public const string LIONPREFAB = "lionprefab";
    }
    public class Listitempanel_prefab
    {
        public const string BundleName = "listitempanel_prefab";
        public const string LISTITEMPANEL = "listitempanel";
    }
    public class Loginpanel_prefab
    {
        public const string BundleName = "loginpanel_prefab";
        public const string LOGINPANEL = "loginpanel";
    }
    public class Mainanimation_prefab
    {
        public const string BundleName = "mainanimation_prefab";
        public const string MAINANIMATION = "mainanimation";
    }
    public class Mainguidepanel_prefab
    {
        public const string BundleName = "mainguidepanel_prefab";
        public const string MAINGUIDEPANEL = "mainguidepanel";
    }
    public class Mainpanel_prefab
    {
        public const string BundleName = "mainpanel_prefab";
        public const string MAINPANEL = "mainpanel";
    }
    public class Mask_audio_png
    {
        public const string BundleName = "mask_audio_png";
        public const string MASK_AUDIO = "mask_audio";
    }
    public class Mask_pic_book_png
    {
        public const string BundleName = "mask_pic_book_png";
        public const string MASK_PIC_BOOK = "mask_pic_book";
    }
    public class Mask_video_png
    {
        public const string BundleName = "mask_video_png";
        public const string MASK_VIDEO = "mask_video";
    }
    public class Maskpanel_prefab
    {
        public const string BundleName = "maskpanel_prefab";
        public const string CLOUDPANEL = "cloudpanel";
    }
    public class Medalanimationpanel_prefab
    {
        public const string BundleName = "medalanimationpanel_prefab";
        public const string MEDALANIMATIONPANEL = "medalanimationpanel";
    }
    public class Medalsharepanel_prefab
    {
        public const string BundleName = "medalsharepanel_prefab";
        public const string MEDALSHAREPANEL = "medalsharepanel";
    }
    public class Messagemaskpanel_prefab
    {
        public const string BundleName = "messagemaskpanel_prefab";
        public const string MESSAGEMASKPANEL = "messagemaskpanel";
    }
    public class Photobrowserpanel_prefab
    {
        public const string BundleName = "photobrowserpanel_prefab";
        public const string PHOTOBROWSERPANEL = "photobrowserpanel";
    }
    public class Playgamepanel_prefab
    {
        public const string BundleName = "playgamepanel_prefab";
        public const string PLAYGAMEPANEL = "playgamepanel";
    }
    public class Prefab
    {
        public const string BundleName = "prefab";
        public const string BOOKDETALPIC = "bookdetalpic";
        public const string BTNBACK = "btnback";
        public const string INTEGRALDESCRIPBG = "integraldescripbg";
        public const string LISTVIEW = "listview";
        public const string LISTVIEWFAMILY = "listviewfamily";
        public const string METEOR = "meteor";
        public const string METEORS = "meteors";
        public const string STAR = "star";
        public const string UISTARS = "uistars";
    }
    public class Settingaddaddressprefab_prefab
    {
        public const string BundleName = "settingaddaddressprefab_prefab";
        public const string SETTINGADDADDRESSPREFAB = "settingaddaddressprefab";
    }
    public class Settingaddressitemprefab_prefab
    {
        public const string BundleName = "settingaddressitemprefab_prefab";
        public const string SETTINGADDRESSITEMPREFAB = "settingaddressitemprefab";
    }
    public class Settingpanel_prefab
    {
        public const string BundleName = "settingpanel_prefab";
        public const string SETTINGPANEL = "settingpanel";
    }
    public class Shitong_ch_mp3
    {
        public const string BundleName = "shitong_ch_mp3";
        public const string SHITONG_CH = "shitong_ch";
    }
    public class Studay_country_mp3
    {
        public const string BundleName = "studay_country_mp3";
        public const string STUDAY_COUNTRY = "studay_country";
    }
    public class Targetdetailpanel_prefab
    {
        public const string BundleName = "targetdetailpanel_prefab";
        public const string TARGETDETAILPANEL = "targetdetailpanel";
    }
    public class Text_baby_exclusive_gift_png
    {
        public const string BundleName = "text_baby_exclusive_gift_png";
        public const string TEXT_BABY_EXCLUSIVE_GIFT = "text_baby_exclusive_gift";
    }
    public class Text_chinese_learning_plan_png
    {
        public const string BundleName = "text_chinese_learning_plan_png";
        public const string TEXT_CHINESE_LEARNING_PLAN = "text_chinese_learning_plan";
    }
    public class Text_english_learning_plan_png
    {
        public const string BundleName = "text_english_learning_plan_png";
        public const string TEXT_ENGLISH_LEARNING_PLAN = "text_english_learning_plan";
    }
    public class Text_exchange_succee_png
    {
        public const string BundleName = "text_exchange_succee_png";
        public const string TEXT_EXCHANGE_SUCCEE = "text_exchange_succee";
    }
    public class Text_received_succee_png
    {
        public const string BundleName = "text_received_succee_png";
        public const string TEXT_RECEIVED_SUCCEE = "text_received_succee";
    }
    public class Tippanel_prefab
    {
        public const string BundleName = "tippanel_prefab";
        public const string TIPPANEL = "tippanel";
    }
    public class Today_is_sunday_mp3
    {
        public const string BundleName = "today_is_sunday_mp3";
        public const string TODAY_IS_SUNDAY = "today_is_sunday";
    }
    public class Toggle_subtract_sel_png
    {
        public const string BundleName = "toggle_subtract_sel_png";
        public const string TOGGLE_SUBTRACT_SEL = "toggle_subtract_sel";
    }
    public class Toggle_transfer_sel_png
    {
        public const string BundleName = "toggle_transfer_sel_png";
        public const string TOGGLE_TRANSFER_SEL = "toggle_transfer_sel";
    }
    public class Tongtongprefab_prefab
    {
        public const string BundleName = "tongtongprefab_prefab";
        public const string TONGTONGPREFAB = "tongtongprefab";
    }
    public class Unlock_book_mp3
    {
        public const string BundleName = "unlock_book_mp3";
        public const string UNLOCK_BOOK = "unlock_book";
    }
    public class Unlock_day_mp3
    {
        public const string BundleName = "unlock_day_mp3";
        public const string UNLOCK_DAY = "unlock_day";
    }
    public class Updatetippanel_prefab
    {
        public const string BundleName = "updatetippanel_prefab";
        public const string UPDATETIPPANEL = "updatetippanel";
    }
    public class Userinfopanel_prefab
    {
        public const string BundleName = "userinfopanel_prefab";
        public const string USERINFOPANEL = "userinfopanel";
    }
    public class Welcome_mp3
    {
        public const string BundleName = "welcome_mp3";
        public const string WELCOME = "welcome";
    }
    public class Workswallitem_prefab
    {
        public const string BundleName = "workswallitem_prefab";
        public const string WORKSWALLITEM = "workswallitem";
    }
    public class Workswallpanel_prefab
    {
        public const string BundleName = "workswallpanel_prefab";
        public const string WORKSWALLPANEL = "workswallpanel";
    }
    public class Xxqg_bg_music_mp3
    {
        public const string BundleName = "xxqg_bg_music_mp3";
        public const string XXQG_BG_MUSIC = "xxqg_bg_music";
    }
}
