//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:dd0a64f9-0548-492d-becf-ea7b6331ee6c
    public partial class AddressPickerPanel
    {
        
        public const string NAME = "AddressPickerPanel";
        
        [SerializeField()]
        public AddressPickerGroup PickerPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        private AddressPickerPanelData mPrivateData = null;
        
        public AddressPickerPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AddressPickerPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            PickerPanel = null;
            BtnCancel = null;
            BtnConfirm = null;
            mData = null;
        }
    }
}
