//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using QFramework;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class AddressPickerPanelData : QFramework.UIPanelData
    {
        public ProvinceModel selectAddress;
    }
    
    public partial class AddressPickerPanel : QFramework.UIPanel
    {
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as AddressPickerPanelData ?? new AddressPickerPanelData();
            Dictionary<string, object> paramDict = new Dictionary<string, object>();
            if (PlayerPrefsUtil.ProvinceModels.IsNull())
            {
                HttpUtil.GetWithSign<List<ProvinceModel>>(UrlConst.ProvinceCityAreaList, paramDict)
                    .Subscribe(response =>
                        {
                            PlayerPrefsUtil.ProvinceModels = response;
                            if (mData.selectAddress != null)
                            {
                                PickerPanel.Init(response, mData.selectAddress);
                            }
                            else
                            {
                                PickerPanel.Init(response);
                            }
                        }
                        , e =>
                        {
                       
                        }).AddTo(this);
            }
            else
            {
                if (mData.selectAddress != null)
                {
                    PickerPanel.Init(PlayerPrefsUtil.ProvinceModels, mData.selectAddress);
                }
                else
                {
                    PickerPanel.Init(PlayerPrefsUtil.ProvinceModels);
                }
            }
            BtnCancel.onClick.AddListener(()=>{
                Back();
            });
            BtnConfirm.onClick.AddListener(()=>{
                SimpleEventSystem.Publish(new SelectAddressDate(PickerPanel.selectAddress));
                Back();
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
