//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:59849995-9f5f-404a-8556-7d8617f912de
    public partial class AttendanceMainPanel
    {
        
        public const string NAME = "AttendanceMainPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAudio;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnPicture;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnVideo;
        
        private AttendanceMainPanelData mPrivateData = null;
        
        public AttendanceMainPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceMainPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            BtnAudio = null;
            BtnPicture = null;
            BtnVideo = null;
            mData = null;
        }
    }
}
