//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:17dbb3dd-a7e1-4500-9cd5-eec51613487c
    public partial class AttendanceAddPanel
    {
        
        public const string NAME = "AttendanceAddPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputContent;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextCount;
        
        [SerializeField()]
        public UnityEngine.RectTransform AddContent;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextAdd;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAdd;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImagePic;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnDel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnVideo;
        
        [SerializeField()]
        public UnityEngine.RectTransform AudioContent;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgPlayAndPause;
        
        [SerializeField()]
        public UnityEngine.Animator ImgPlaying;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnPlayAndPause;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTime;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClose;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnPush;
        
        private AttendanceAddPanelData mPrivateData = null;
        
        public AttendanceAddPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceAddPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            InputContent = null;
            TextCount = null;
            AddContent = null;
            TextAdd = null;
            BtnAdd = null;
            ImagePic = null;
            BtnDel = null;
            BtnVideo = null;
            AudioContent = null;
            ImgPlayAndPause = null;
            ImgPlaying = null;
            BtnPlayAndPause = null;
            TextTime = null;
            BtnClose = null;
            BtnCancel = null;
            BtnPush = null;
            mData = null;
        }
    }
}
