//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:0a6be921-51c6-42f9-8afe-79a33b8b2761
    public partial class AttendanceSharePanel
    {
        
        public const string NAME = "AttendanceSharePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageContent;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextContent;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageSubject;
        
        [SerializeField()]
        public CircleImage ImageHead;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextName;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextCount;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSaveAlbum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnShareWechat;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnShareWechatMoments;
        
        private AttendanceSharePanelData mPrivateData = null;
        
        public AttendanceSharePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceSharePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ImageContent = null;
            TextContent = null;
            ImageSubject = null;
            ImageHead = null;
            TextName = null;
            TextCount = null;
            BtnSaveAlbum = null;
            BtnShareWechat = null;
            BtnShareWechatMoments = null;
            mData = null;
        }
    }
}
