//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:a92d7db0-20b2-42fc-8d2e-09675ef3fc2d
    public partial class AttendanceInstructionsPanel
    {
        
        public const string NAME = "AttendanceInstructionsPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Button ButtonConfirm;
        
        private AttendanceInstructionsPanelData mPrivateData = null;
        
        public AttendanceInstructionsPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceInstructionsPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ButtonConfirm = null;
            mData = null;
        }
    }
}
