//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:fca49ea0-805e-4ff6-9bd8-a41b264283ef
    public partial class AttendanceSelectPanel
    {
        
        public const string NAME = "AttendanceSelectPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button ButtonCover;
        
        [SerializeField()]
        public UnityEngine.UI.Button ButtonChinese;
        
        [SerializeField()]
        public UnityEngine.UI.Button ButtonEnglish;
        
        private AttendanceSelectPanelData mPrivateData = null;
        
        public AttendanceSelectPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceSelectPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ButtonCover = null;
            ButtonChinese = null;
            ButtonEnglish = null;
            mData = null;
        }
    }
}
