//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:1ad0dd1d-af40-4f40-b0cc-0598002365d2
    public partial class AttendanceRulePanel
    {
        
        public const string NAME = "AttendanceRulePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgWaterMask;
        
        private AttendanceRulePanelData mPrivateData = null;
        
        public AttendanceRulePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AttendanceRulePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ImgWaterMask = null;
            mData = null;
        }
    }
}
