//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:3067346b-2cea-4f6d-a413-e0f5270e3e4b
    public partial class BaByInfoPanel
    {
        
        public const string NAME = "BaByInfoPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform BabyPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBabyMask;
        
        [SerializeField()]
        public CircleImage ImgBabyHead;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputName;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBirthday;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextBirthday;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBoy;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnGirl;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBabyConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text Text;
        
        private BaByInfoPanelData mPrivateData = null;
        
        public BaByInfoPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BaByInfoPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            BabyPanel = null;
            BtnBabyMask = null;
            ImgBabyHead = null;
            InputName = null;
            BtnBirthday = null;
            TextBirthday = null;
            BtnBoy = null;
            BtnGirl = null;
            BtnBabyConfirm = null;
            Text = null;
            mData = null;
        }
    }
}
