//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;
using UniRx;
using SuperKid.Utils;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class BindConfirmBootPanelData : QFramework.UIPanelData
    {
        public bool isFromAudio;
        public bool isFromSetting;
    }
    
    public partial class BindConfirmBootPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as BindConfirmBootPanelData ?? new BindConfirmBootPanelData();
            // please add init code here
            BtnBack.OnClickAsObservable().Subscribe((unit =>
            {
                AudioManager.PlaySound("Button_Audio");
                BackClick();
            })).AddTo(this);

            BtnConfirm.OnClickAsObservable().Subscribe((unit =>
            {
                AudioManager.PlaySound("Button_Audio");
                UIMgr.OpenPanel<BindWIFIMessagePanel>(new BindWIFIMessagePanelData(),UITransitionType.CIRCLE, this);
            })).AddTo(this);
        }

        void BackClick()
        {
            if (mData.isFromAudio)
            {
                CommonUtil.OpenCloudMain(this);
            } 
            else
            {
                Back();
            }
        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
