//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.Tweening;
using SuperKid.Utils;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    
    public class BindGuidePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class BindGuidePanel : QFramework.UIPanel
    {

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as BindGuidePanelData ?? new BindGuidePanelData();
            ButtonGuide.transform.DOLocalMoveY(1f, 2f).SetEase(Ease.Linear).SetLoops(-1,LoopType.Yoyo);
            Meteors.transform.DOLocalMoveX(-2370, 5f).SetLoops(-1, LoopType.Restart);
            Meteors.transform.DOLocalMoveY(-470, 5f).SetLoops(-1, LoopType.Restart);
            // ButtonGuide.transform.DOLocalRotate(3f, 3f,RotateMode.FastBeyond360).SetLoops(-1,LoopType.Yoyo);
            
            // 绑定
            ButtonGuide.OnClickAsObservable().Subscribe((unit =>
            {
                AudioManager.PlaySound("Button_Audio");
                Debug.Log("绑定");
                
                AudioManager.PlaySound("Button_Audio");
                UIMgr.OpenPanel<BindConfirmBootPanel>(new BindConfirmBootPanelData(),UITransitionType.CIRCLE, this);
            })).AddTo(this);

            BtnBack.OnClickAsObservable().Subscribe(_ =>
            {
                AudioManager.PlaySound("Button_Audio");
                Back();
            }).AddTo(this);
            BtnSkipGuide.OnClickAsObservable().Subscribe((unit =>
            {
                AudioManager.PlaySound("Button_Audio");
                Debug.Log("随便听听跳过");
                CommonUtil.OpenCloudMain(this);
            })).AddTo(this);
            // please add init code here
        }

        protected override void OnClose()
        {
            Meteors.DOKill();
            ButtonGuide.DOKill();
        }
    }
}
