//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:fb083a3a-f010-4622-99a3-28e6e04492b4
    public partial class BindConfirmBootPanel
    {
        
        public const string NAME = "BindConfirmBootPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        private BindConfirmBootPanelData mPrivateData = null;
        
        public BindConfirmBootPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BindConfirmBootPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            BtnConfirm = null;
            mData = null;
        }
    }
}
