//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:15a79918-01f3-4e07-86e2-f63d7e54e529
    public partial class BindWIFIMessagePanel
    {
        
        public const string NAME = "BindWIFIMessagePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCommit;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgDetermine;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputFieldSSID;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSSIDList;
        
        [SerializeField()]
        public CanHideInputField InputFieldPWD;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnShow;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClearPWD;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSavepwd;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageSavePWD;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConnectTips;
        
        private BindWIFIMessagePanelData mPrivateData = null;
        
        public BindWIFIMessagePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BindWIFIMessagePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            BtnCommit = null;
            ImgDetermine = null;
            InputFieldSSID = null;
            BtnSSIDList = null;
            InputFieldPWD = null;
            BtnShow = null;
            BtnClearPWD = null;
            BtnSavepwd = null;
            ImageSavePWD = null;
            BtnConnectTips = null;
            mData = null;
        }
    }
}
