//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:f40f70d7-adca-4c5b-b7be-c0e6a0548bf5
    public partial class BindCheckWIFIPanel
    {
        
        public const string NAME = "BindCheckWIFIPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform Meteors;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnDetermineWiFi;
        
        private BindCheckWIFIPanelData mPrivateData = null;
        
        public BindCheckWIFIPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BindCheckWIFIPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            Meteors = null;
            BtnDetermineWiFi = null;
            mData = null;
        }
    }
}
