//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:79151d18-6aec-420d-8810-23fd1e42e558
    public partial class BookDetailPanel
    {
        
        public const string NAME = "BookDetailPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgThumb;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvPicBookIns;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvContentIns;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnStart;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvName;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvAuth;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private BookDetailPanelData mPrivateData = null;
        
        public BookDetailPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BookDetailPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgThumb = null;
            TvTitle = null;
            TvPicBookIns = null;
            TvContentIns = null;
            BtnStart = null;
            TvName = null;
            TvAuth = null;
            BtnBack = null;
            mData = null;
        }
    }
}
