//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:d0158036-0d40-45cf-ae92-70668b8d5b60
    public partial class BookDayListPanel
    {
        
        public const string NAME = "BookDayListPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBookDayListBack;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnTarget;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBook;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAudio;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnVideo;
        
        [SerializeField()]
        public BookMonth BookMonthObj;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBookMonthBack;
        
        private BookDayListPanelData mPrivateData = null;
        
        public BookDayListPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BookDayListPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBookDayListBack = null;
            BtnTitle = null;
            TvTitle = null;
            BtnTarget = null;
            BtnBook = null;
            BtnAudio = null;
            BtnVideo = null;
            BookMonthObj = null;
            BtnBookMonthBack = null;
            mData = null;
        }
    }
}
