//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:d83f7753-0826-43b6-aafd-4fc2d8851120
    public partial class BookDayPanel
    {
        
        public const string NAME = "BookDayPanel";
        
        [SerializeField()]
        public UnityEngine.RectTransform Content;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgDay;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvDayNum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAttendance;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private BookDayPanelData mPrivateData = null;
        
        public BookDayPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new BookDayPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Content = null;
            TvTitle = null;
            ImgDay = null;
            TvDayNum = null;
            BtnAttendance = null;
            BtnBack = null;
            mData = null;
        }
    }
}
