//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    public class BookDetailPanelData : QFramework.UIPanelData
    {
        public DayActionModel DayActionModel;
    }
    
    public partial class BookDetailPanel : QFramework.UIPanel
    {
        protected override void OnInit(QFramework.IUIData uiData)
        { 
            AudioManager.SetMusicOff();
            mData = uiData as BookDetailPanelData ?? new BookDetailPanelData();
            TvAuth.text=mData.DayActionModel.author.IsNullOrEmpty()?string.Empty:"作者:" + mData.DayActionModel.author;
           TvTitle.text = mData.DayActionModel.title;
           TvName.text = mData.DayActionModel.name;
           TvContentIns.text = mData.DayActionModel.contentIntroduction;
           TvPicBookIns.text = mData.DayActionModel.picBookIntroduction;
           ImageDownloadUtils.Instance.SetAsyncImage(mData.DayActionModel.thumbUrl,ImgThumb);
           BtnStart.onClick.AddListener(()=>{
               AudioManager.PlaySound("Button_Audio");
                   // 跳转原生传参
                   var param = new Dictionary<string, object>();
                   var subParam = new Dictionary<string, object>();
                   subParam.Add("picBookId", mData.DayActionModel.resourceId);
                   if (Application.platform == RuntimePlatform.Android)
                   {
                       param.Add("target", AppConst.BOOK_ANDROID);
                       param.Add("params", subParam); 
                       AndroidForUnity.CallAndroidStartActivityForAnim(param.ToJson(), AppConst.ANIM_CIRCLE);
                   }
                   else
                   {
                       param.Add("target", AppConst.BOOK_IOS);
                       param.Add("params", subParam); 
                       IOSClientUtil.CallIOSClient(param.ToJson());
                   }
           });
           BtnBack.onClick.AddListener(() =>
           {
               AudioManager.PlaySound("Button_Audio");
               Back();
           });

        }
        

        protected override void OnClose()
        {
            AudioManager.SetMusicOn();
        }
    }
}
