//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:cf92ee4a-a6b1-419d-852a-fbdbd874293b
    public partial class ChoosePhotoPanel
    {
        
        public const string NAME = "ChoosePhotoPanel";
        
        [SerializeField()]
        public DatePickerGroup Panel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAlbum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCamera;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextCamera;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTip;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        private ChoosePhotoPanelData mPrivateData = null;
        
        public ChoosePhotoPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ChoosePhotoPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Panel = null;
            BtnAlbum = null;
            BtnCamera = null;
            TextCamera = null;
            TextTip = null;
            BtnCancel = null;
            mData = null;
        }
    }
}
