//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:152231e4-f7a7-4671-81f8-aaaa22deb17e
    public partial class CollectGiftBoxPanel
    {
        
        public const string NAME = "CollectGiftBoxPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgSuccess;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgName;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCheck;
        
        private CollectGiftBoxPanelData mPrivateData = null;
        
        public CollectGiftBoxPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new CollectGiftBoxPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgSuccess = null;
            ImgName = null;
            BtnCheck = null;
            mData = null;
        }
    }
}
