//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:e9d1cc53-ba6a-46ff-bfe9-c046dd6392aa
    public partial class ConnectDevicePanel
    {
        
        public const string NAME = "ConnectDevicePanel";
        
        [SerializeField()]
        public UnityEngine.RectTransform Meteors;
        
        [SerializeField()]
        public UnityEngine.RectTransform ConnectingContent;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCheckWiFi;
        
        [SerializeField()]
        public UnityEngine.Animator ConnectIngImage;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextConnect;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private ConnectDevicePanelData mPrivateData = null;
        
        public ConnectDevicePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ConnectDevicePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Meteors = null;
            ConnectingContent = null;
            BtnCheckWiFi = null;
            ConnectIngImage = null;
            TextConnect = null;
            BtnBack = null;
            mData = null;
        }
    }
}
