//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:f5a672fb-9b10-4ba8-8626-4f5a539d795d
    public partial class CreateOrderPanel
    {
        
        public const string NAME = "CreateOrderPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgWaterMask;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTitle;
        
        [SerializeField()]
        public UnityEngine.RectTransform EditAddress;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextUserAddress;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnEditAddress;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextUserName;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextUserMobile;
        
        [SerializeField()]
        public UnityEngine.RectTransform PlusAddress;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnPlusAddress;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgGoodIcon;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextGoodName;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextGoodScore;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextGoodPrice;
        
        [SerializeField()]
        public UnityEngine.RectTransform MakeOrder;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextExchangeScore;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        [SerializeField()]
        public UnityEngine.RectTransform ShowOrder;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextOderNum;
        
        private CreateOrderPanelData mPrivateData = null;
        
        public CreateOrderPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new CreateOrderPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ImgWaterMask = null;
            TextTitle = null;
            EditAddress = null;
            TextUserAddress = null;
            BtnEditAddress = null;
            TextUserName = null;
            TextUserMobile = null;
            PlusAddress = null;
            BtnPlusAddress = null;
            ImgGoodIcon = null;
            TextGoodName = null;
            TextGoodScore = null;
            TextGoodPrice = null;
            MakeOrder = null;
            TextExchangeScore = null;
            BtnConfirm = null;
            ShowOrder = null;
            TextOderNum = null;
            mData = null;
        }
    }
}
