//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:eb5a0530-5b54-4048-95f7-fa00e60513c7
    public partial class DailyTaskPanel
    {
        
        public const string NAME = "DailyTaskPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgWaterMask;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextAttendanceScoreConfig;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAttendance;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageAttendanceDone;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextPunchScoreConfig;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextPunchScoreShareConfig;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnPunch;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextSignInDayNum;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextClockNum;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTaskShareNum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnTaskRule;
        
        [SerializeField()]
        public UnityEngine.RectTransform MedalScrollView;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextMedalStudyDaysNum;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextMedalNum;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextMedalShareNum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnMedalRule;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleDailyTask;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleDailyMedal;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnIntegralRule;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnIntegral;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextIntegralNum;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnExchange;
        
        private DailyTaskPanelData mPrivateData = null;
        
        public DailyTaskPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new DailyTaskPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ImgWaterMask = null;
            TextAttendanceScoreConfig = null;
            BtnAttendance = null;
            ImageAttendanceDone = null;
            TextPunchScoreConfig = null;
            TextPunchScoreShareConfig = null;
            BtnPunch = null;
            TextSignInDayNum = null;
            TextClockNum = null;
            TextTaskShareNum = null;
            BtnTaskRule = null;
            MedalScrollView = null;
            TextMedalStudyDaysNum = null;
            TextMedalNum = null;
            TextMedalShareNum = null;
            BtnMedalRule = null;
            ToggleDailyTask = null;
            ToggleDailyMedal = null;
            BtnIntegralRule = null;
            BtnIntegral = null;
            TextIntegralNum = null;
            BtnExchange = null;
            mData = null;
        }
    }
}
