//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:75019d3e-886e-470f-9e5f-6ad8d4a4599e
    public partial class DatePickerPanel
    {
        
        public const string NAME = "DatePickerPanel";
        
        [SerializeField()]
        public DatePickerGroup PickerPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        private DatePickerPanelData mPrivateData = null;
        
        public DatePickerPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new DatePickerPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            PickerPanel = null;
            BtnCancel = null;
            BtnConfirm = null;
            mData = null;
        }
    }
}
