//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:1c42040f-5a55-4cdd-b36b-2601c67df29f
    public partial class DeviceStatusPanel
    {
        
        public const string NAME = "DeviceStatusPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform Meteors;
        
        [SerializeField()]
        public SeekCtrl SliderDeviceVoice;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextProgress;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBattery;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextBattery;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageBattery;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConnect;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextConnect;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImageConnect;
        
        private DeviceStatusPanelData mPrivateData = null;
        
        public DeviceStatusPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new DeviceStatusPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            Meteors = null;
            SliderDeviceVoice = null;
            TextProgress = null;
            BtnBattery = null;
            TextBattery = null;
            ImageBattery = null;
            BtnConnect = null;
            TextConnect = null;
            ImageConnect = null;
            mData = null;
        }
    }
}
