//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:39dd1b30-4db1-43b5-92ea-e309561ba610
    public partial class FamilyAddPanel
    {
        
        public const string NAME = "FamilyAddPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform Panel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text Text;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputMobile;
        
        private FamilyAddPanelData mPrivateData = null;
        
        public FamilyAddPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new FamilyAddPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            Panel = null;
            BtnConfirm = null;
            Text = null;
            InputMobile = null;
            mData = null;
        }
    }
}
