//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;
using SuperKid.Utils;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class FamilyAddPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class FamilyAddPanel : QFramework.UIPanel
    {

        public string relation;
        private Texture2D texture2DNor, texture2DSel;
        private ResLoader mResLoader = ResLoader.Allocate();

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as FamilyAddPanelData ?? new FamilyAddPanelData();
            // please add init code here
            BtnBack.onClick.AddListener(() =>
            {
                AudioManager.PlaySound("Button_Audio");
                Back();
            });
            BtnConfirm.enabled = false;
            texture2DSel = mResLoader.LoadSync<Texture2D>("btn_code_sel");
            texture2DNor = mResLoader.LoadSync<Texture2D>("btn_code_nor");
            InputMobile.onValueChange.AddListener(Change);
            BtnConfirm.onClick.AddListener(() =>
            {
                AudioManager.PlaySound("Button_Audio");
                StartResquestForDelBabyAddress();
            });
        }
        
        private void StartResquestForDelBabyAddress()
        {
            Dictionary<string, object> paramDict = new Dictionary<string, object>();
            paramDict.Add("inviteId", PlayerPrefsUtil.GetUserId());
            paramDict.Add("inviteeMobile", InputMobile.text);
            paramDict.Add("inviteeBabyRelation", relation);
            HttpUtil.PostWithSign<int>(UrlConst.DoCheckInviteValid, paramDict)
                .Subscribe(response =>
                    {
                        if(response == 1) {
                            Dictionary<string, object> message = new Dictionary<string, object>();
                            message.Add("mobile", InputMobile.text);
                            message.Add("content","【环球少儿app】邀请你加入，快来跟我一起读绘本吧！");
                            NativeGallery.GetSomethingFromNative((json, action) =>
                            {
                                
                            }, (int) NativeAction.SendSMS, message.ToJson());
                        }
                        CommonUtil.toast("邀请成功");
                        SimpleEventSystem.Publish(new UpdateBaseInfoDate(true));
                        Back();
                    }
                    , e =>
                    { 
                        if (e is HttpException)
                        {
                            HttpException http = e as HttpException;
                            Log.E("弹吐司" + http.Message);
                        }
                    }).AddTo(this);
            
        }
        
        public void setRelation(string relation)
        {
            AudioManager.PlaySound("Button_Audio");
            this.relation = relation;
            Log.I("relation: " + relation);
        }

        void Change(string str)
        {
            if (!str.IsNullOrEmpty())
            {
                BtnConfirm.image.sprite = Sprite.Create(texture2DNor, new Rect(0, 0, texture2DNor.width, texture2DNor.height), Vector2.one * 0.5f);
                BtnConfirm.enabled = true;
            }
            else
            {
                BtnConfirm.image.sprite = Sprite.Create(texture2DSel, new Rect(0, 0, texture2DSel.width, texture2DSel.height), Vector2.one * 0.5f);
                BtnConfirm.enabled = false;
            }
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
            mResLoader.Recycle2Cache();
            mResLoader = null;
        }
    }
    
}
