//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:00ab4e97-4aa7-40ba-a360-caee443bbdfc
    public partial class FGUIPanel
    {
        
        public const string NAME = "FGUIPanel";
        
        private FGUIPanelData mPrivateData = null;
        
        public FGUIPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new FGUIPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
