//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:72974304-9736-4d6e-999e-4bf9eed09ea6
    public partial class HistoricalPhotoWallPanel
    {
        
        public const string NAME = "HistoricalPhotoWallPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.ScrollRect PhotoWallScrollView;
        
        private HistoricalPhotoWallPanelData mPrivateData = null;
        
        public HistoricalPhotoWallPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new HistoricalPhotoWallPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            PhotoWallScrollView = null;
            mData = null;
        }
    }
}
