//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SuperKid.Entity;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    
    public class HistoricalPhotoWallPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class HistoricalPhotoWallPanel : QFramework.UIPanel
    {
        private ResLoader mResLoader = ResLoader.Allocate();

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as HistoricalPhotoWallPanelData ?? new HistoricalPhotoWallPanelData();

            BtnBack.OnClickAsObservable().Subscribe(_ =>
            {
                AudioManager.PlaySound("Button_Audio");
                Back();
            }).AddTo(this);
            Dictionary<string, object> paramDict = new Dictionary<string, object>();

            paramDict.Add("babyId", PlayerPrefsUtil.GetBabyId());
            Debug.Log(paramDict);
            HttpUtil.GetWithSign<List<PhotoWallModel>>(UrlConst.FindPhotoWall, paramDict)
                .Subscribe(response =>
                    {
                        this.CreatMedalItem(response);
                        Debug.Log("------"+ response);
                    }
                    , e =>
                    {
                        if (e is HttpException)
                        {
                            HttpException http = e as HttpException;
                            Log.E("弹吐司" + http.Message);
                        }
                    }).AddTo(this);
            
            // please add init code here
        }
        
        
        /**
         * 展示 照片墙数据
         */
        private void CreatMedalItem(List<PhotoWallModel> modelslist)
        {
            Debug.Log("初始化 Medal 相关信息 ");
            foreach (var model in modelslist)
            {
                mResLoader.LoadSync<GameObject>("ItemHistoryPhotoWallPanel")
                    .Instantiate()
                    .transform
                    .LocalIdentity()
                    .Parent(PhotoWallScrollView.transform.Find("Viewport").Find("Content"))
                    .LocalScale(1, 1, 1)
                    .ApplySelfTo(ItemPhotoWallPanel =>
                        {
                            var userImg = ItemPhotoWallPanel.transform.Find("ImgMask").Find("ImgUserPhoto").GetComponent<Image>();
                            var photoButton = ItemPhotoWallPanel.transform.Find("Button").GetComponent<Button>();
                            ImageDownloadUtils.Instance.SetAsyncImage(model.studyDetailUrl, userImg);
                            photoButton.OnClickAsObservable().Subscribe(_ =>
                            {
                                AudioManager.PlaySound("Button_Audio");
                                Debug.Log("点击了照片墙,某张照片");
                                // if (Application.platform == RuntimePlatform.Android)
                                // {
                                //     AndroidForUnity.CallAndroidForShowPic(model.studyDetailUrl);
                                // }
                                UIMgr.OpenPanel<PhotoBrowserPanel>(new PhotoBrowserPanelData()
                                {
                                    ImageUrl = model.studyDetailUrl,
                                },UITransitionType.NULL);
                            }).AddTo(this);
                        });
            }
            
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
            mResLoader.Recycle2Cache();
            mResLoader = null;
        }
    }
}
