//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:d33881b3-c510-4833-b55d-de138c578780
    public partial class IntegralDescripPanel
    {
        
        public const string NAME = "IntegralDescripPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgWaterMask;
        
        [SerializeField()]
        public UnityEngine.UI.ScrollRect IntegralScrollView;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private IntegralDescripPanelData mPrivateData = null;
        
        public IntegralDescripPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new IntegralDescripPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgWaterMask = null;
            IntegralScrollView = null;
            BtnBack = null;
            mData = null;
        }
    }
}
