//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:c93723cd-b6a8-4863-a52b-70dc411512be
    public partial class IntegralDetailPanel
    {
        
        public const string NAME = "IntegralDetailPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgWaterMask;
        
        [SerializeField()]
        public UnityEngine.UI.Image ExchangeRecordPanel;
        
        [SerializeField()]
        public UnityEngine.UI.ScrollRect ExchangeScrollView;
        
        [SerializeField()]
        public UnityEngine.RectTransform ExchangeNODataContent;
        
        [SerializeField()]
        public UnityEngine.UI.Image IntegralRecordPanel;
        
        [SerializeField()]
        public UnityEngine.UI.ScrollRect IntegralGetScrollView;
        
        [SerializeField()]
        public UnityEngine.RectTransform RecordNODataContent;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle IntegralExChangelToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle IntegralRecorderToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private IntegralDetailPanelData mPrivateData = null;
        
        public IntegralDetailPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new IntegralDetailPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgWaterMask = null;
            ExchangeRecordPanel = null;
            ExchangeScrollView = null;
            ExchangeNODataContent = null;
            IntegralRecordPanel = null;
            IntegralGetScrollView = null;
            RecordNODataContent = null;
            IntegralExChangelToggle = null;
            IntegralRecorderToggle = null;
            BtnBack = null;
            mData = null;
        }
    }
}
