//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:9998d641-b319-46b2-9f78-9718fd862390
    public partial class ListItemPanel
    {
        
        public const string NAME = "ListItemPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button ImgPicBook;
        
        [SerializeField()]
        public UnityEngine.UI.Button ImgAudio;
        
        [SerializeField()]
        public UnityEngine.UI.Button ImgVideo;
        
        [SerializeField()]
        public UnityEngine.UI.Image NoData;
        
        [SerializeField()]
        public UnityEngine.RectTransform VideoScrollView;
        
        [SerializeField()]
        public UnityEngine.RectTransform AudioScrollView;
        
        [SerializeField()]
        public UnityEngine.RectTransform PicBookScrollView;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        private ListItemPanelData mPrivateData = null;
        
        public ListItemPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new ListItemPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgPicBook = null;
            ImgAudio = null;
            ImgVideo = null;
            NoData = null;
            VideoScrollView = null;
            AudioScrollView = null;
            PicBookScrollView = null;
            BtnBack = null;
            mData = null;
        }
    }
}
