//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:2458d9a2-8229-41ab-b4d7-c410c5d5754b
    public partial class LoginPanel
    {
        
        public const string NAME = "LoginPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCloud1;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCloud2;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgCloud3;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgHyrogen;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform PhonePanel;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputPhone;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClearPhone;
        
        [SerializeField()]
        public UnityEngine.RectTransform CodePanel;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTip;
        
        [SerializeField()]
        public UnityEngine.UI.InputField InputCode;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCode;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextBtnCode;
        
        [SerializeField()]
        public UnityEngine.RectTransform PwdPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextPwdTitle;
        
        [SerializeField()]
        public CanHideInputField InputPwd;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClearPwd;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnHideOrShow;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImgHideOrShow;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnForget;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        private LoginPanelData mPrivateData = null;
        
        public LoginPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new LoginPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgCloud1 = null;
            ImgCloud2 = null;
            ImgCloud3 = null;
            ImgHyrogen = null;
            BtnBack = null;
            PhonePanel = null;
            InputPhone = null;
            BtnClearPhone = null;
            CodePanel = null;
            TextTip = null;
            InputCode = null;
            BtnCode = null;
            TextBtnCode = null;
            PwdPanel = null;
            TextPwdTitle = null;
            InputPwd = null;
            BtnClearPwd = null;
            BtnHideOrShow = null;
            ImgHideOrShow = null;
            BtnForget = null;
            BtnConfirm = null;
            mData = null;
        }
    }
}
