//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;
using SimpleEventSystem = QFramework.SimpleEventSystem;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using Entity;
    using QFramework;
    
    public class MedalAnimationPanelData : QFramework.UIPanelData
    {
        public MedalModel.MedalBean medalModel;
    }
    
    public partial class MedalAnimationPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MedalAnimationPanelData ?? new MedalAnimationPanelData();

            TvMedalDay.text = "第一天";
            TvMedalName.text = String.Format("\"{0}\"勋章",mData.medalModel.medalName);
            TvMedalDay.text = String.Format("第{0}天",mData.medalModel.medalGrade);

            BtnMedalReceived.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("勋章点击领取");
                RequestDrawMedal();
            }).AddTo(this);

            // please add init code here
        }

        private void RequestDrawMedal()
        {
            Dictionary<string, object> paramDict = new Dictionary<string, object>();
            paramDict.Add("babyId",PlayerPrefsUtil.GetBabyId());
            paramDict.Add("medalGrade",mData.medalModel.medalGrade);
            
            HttpUtil.PostWithSign<object>(UrlConst.DrawMedal, paramDict)
                .Subscribe(result =>
                {
                    UIMgr.OpenPanel<MedalSharePanel>(new MedalSharePanelData()
                    {
                        medalModel = mData.medalModel,
                    },UITransitionType.CLOUD);
                    Back();
                    SimpleEventSystem.Publish(new MedalDrawSuccess());
                }, exception =>
                {
                    
                }).AddTo(this);
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
