//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:3a2f5af8-6901-4bde-8171-e12c99e20e49
    public partial class MedalAnimationPanel
    {
        
        public const string NAME = "MedalAnimationPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TvMedalDay;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvMedalName;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnMedalReceived;
        
        private MedalAnimationPanelData mPrivateData = null;
        
        public MedalAnimationPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MedalAnimationPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TvMedalDay = null;
            TvMedalName = null;
            BtnMedalReceived = null;
            mData = null;
        }
    }
}
