//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:e2fef9f5-9c37-4888-8df2-df2d439a40ae
    public partial class MessageMaskPanel
    {
        
        public const string NAME = "MessageMaskPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnClick;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvContent;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvTitle;
        
        private MessageMaskPanelData mPrivateData = null;
        
        public MessageMaskPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new MessageMaskPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnClick = null;
            TvContent = null;
            TvTitle = null;
            mData = null;
        }
    }
}
