//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class MessageMaskPanelData : QFramework.UIPanelData
    {
        public string Title = string.Empty;
        public string Content = string.Empty;
    }
    
    public partial class MessageMaskPanel : QFramework.UIPanel
    {

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as MessageMaskPanelData ?? new MessageMaskPanelData();
            SimpleEventSystem.Publish(new CanvasDotMove());
            TvContent.text = mData.Content;
            TvTitle.text = mData.Title;
            BtnClick.onClick.AddListener(() => { Back();});
        }

        protected override void OnClose()
        {
            SimpleEventSystem.Publish(new CanvasCanMove());
        }
    }
}
