//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    
    public class PhotoBrowserPanelData : QFramework.UIPanelData
    {
        public string ImageUrl = String.Empty;
    }
    
    public partial class PhotoBrowserPanel : QFramework.UIPanel
    {
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PhotoBrowserPanelData ?? new PhotoBrowserPanelData();
            ButtonCover.OnClickAsObservable().Subscribe(_ =>
            {
                AudioManager.PlaySound("Button_Audio");
                Back();
            }).AddTo(this);
            if (mData.ImageUrl.IsNotNullAndEmpty())
            {
                if (mData.ImageUrl.Contains("http"))
                {
                    ImageDownloadUtils.Instance.SetAsyncImage(mData.ImageUrl, ImagePhoto);
                }
                else
                {
                    ImageDownloadUtils.Instance.SetAsyncImage("file://" + mData.ImageUrl, ImagePhoto);

                }
            }
            // please add init code here
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
