//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:5e9fd9e7-7530-4af6-9c9b-385b98c34d78
    public partial class PhotoBrowserPanel
    {
        
        public const string NAME = "PhotoBrowserPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button ButtonCover;
        
        [SerializeField()]
        public UnityEngine.UI.Image ImagePhoto;
        
        private PhotoBrowserPanelData mPrivateData = null;
        
        public PhotoBrowserPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PhotoBrowserPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ButtonCover = null;
            ImagePhoto = null;
            mData = null;
        }
    }
}
