//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:55bebf87-44e0-4523-90f2-31471dcff7f1
    public partial class SettingPanel
    {
        
        public const string NAME = "SettingPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ToggleDevice;
        
        [SerializeField()]
        public BaseInfoPanel BaseInfoPanel;
        
        [SerializeField()]
        public AddressManagePanel AddressManagerPanel;
        
        [SerializeField()]
        public ModifyPasswordPanel ModifyPasswordPanel;
        
        [SerializeField()]
        public DevicePanel DevicePanel;
        
        [SerializeField()]
        public ClearCachePanel ClearCachePanel;
        
        [SerializeField()]
        public FeedBackPanel FeedBackPanel;
        
        [SerializeField()]
        public PrivacyPanel PrivacyPanel;
        
        [SerializeField()]
        public UserAgreementPanel UserAgreementPanel;
        
        [SerializeField()]
        public AboutPanel AboutUsPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnLogout;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnShare;
        
        private SettingPanelData mPrivateData = null;
        
        public SettingPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SettingPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            ToggleDevice = null;
            BaseInfoPanel = null;
            AddressManagerPanel = null;
            ModifyPasswordPanel = null;
            DevicePanel = null;
            ClearCachePanel = null;
            FeedBackPanel = null;
            PrivacyPanel = null;
            UserAgreementPanel = null;
            AboutUsPanel = null;
            BtnLogout = null;
            BtnShare = null;
            mData = null;
        }
    }
}
