//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;
using UniRx;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class TargetDetailPanelData : QFramework.UIPanelData
    {
        public BoxModel BoxModel;
    }
    
    public partial class TargetDetailPanel : QFramework.UIPanel
    {

        protected override void OnInit(QFramework.IUIData uiData)
        {
            AudioManager.SetMusicOff();
            mData = uiData as TargetDetailPanelData ?? new TargetDetailPanelData();
            BtnBack.onClick.AddListener(() =>
            {
                AudioManager.PlaySound("Button_Audio");
                Back();
            });
            TvTitle.text = mData.BoxModel.name + "第" + mData.BoxModel.month + "个月";
            TvContent.text = mData.BoxModel.intro;
        }

        protected override void OnClose()
        {
             
        }
    }
}
