//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:803acd14-ecc1-481f-a2da-21a590d82d28
    public partial class TargetDetailPanel
    {
        
        public const string NAME = "TargetDetailPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Text TvContent;
        
        private TargetDetailPanelData mPrivateData = null;
        
        public TargetDetailPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new TargetDetailPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            TvTitle = null;
            TvContent = null;
            mData = null;
        }
    }
}
