//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:7b5d968b-5569-4382-b83a-084c17ab8501
    public partial class TipPanel
    {
        
        public const string NAME = "TipPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTip;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTitle;
        
        private TipPanelData mPrivateData = null;
        
        public TipPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new TipPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TextTip = null;
            BtnCancel = null;
            TextCancel = null;
            BtnConfirm = null;
            TextConfirm = null;
            TextTitle = null;
            mData = null;
        }
    }
}
