//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QFramework;
using SuperKid.Utils;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class TipPanelData : QFramework.UIPanelData
    {
        public TipAction action;
        public string message;
        public bool isHideCancelButton;
        public bool isHideConfirmButton;
        public bool removeConfirmCallback;
        public string strCancel;
        public string strConfirm;
        public string strTitle;
    }
    
    public partial class TipPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as TipPanelData ?? new TipPanelData();
            if (mData.isHideConfirmButton)
            {
                BtnConfirm.gameObject.SetActive(false);
            }
            if (mData.isHideCancelButton)
            {
                BtnCancel.gameObject.SetActive(false);
            }
            if (mData.strCancel.IsNotNullAndEmpty())
            {
                TextCancel.text = mData.strCancel;
            }
            if (mData.strConfirm.IsNotNullAndEmpty())
            {
                TextConfirm.text = mData.strConfirm;
            }
            if (mData.strTitle.IsNotNullAndEmpty())
            {
                TextTitle.text = mData.strTitle;
            }
            TextTip.text = mData.message;
            // please add init code here
            BtnCancel.onClick.AddListener(()=>{
                Back();
            });
            BtnConfirm.onClick.AddListener(()=>{
                if (!mData.removeConfirmCallback)
                {
                    SimpleEventSystem.Publish(new TipConfirmClick(mData.action));
                }
                Back();
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
