//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:c1a1c3a1-3f3a-4827-9def-c7a8ddfb84c6
    public partial class UpdateTipPanel
    {
        
        public const string NAME = "UpdateTipPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTip;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextCancel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextVersion;
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTitle;
        
        private UpdateTipPanelData mPrivateData = null;
        
        public UpdateTipPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UpdateTipPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TextTip = null;
            BtnCancel = null;
            TextCancel = null;
            BtnConfirm = null;
            TextConfirm = null;
            TextVersion = null;
            TextTitle = null;
            mData = null;
        }
    }
}
