//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SuperKid.Utils;

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UpdateTipPanelData : QFramework.UIPanelData
    {
        public string message;
        public string url;
        public bool isHideCancelButton;
        public bool isHideConfirmButton;
        public string version;
    }
    
    public partial class UpdateTipPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UpdateTipPanelData ?? new UpdateTipPanelData();
            if (mData.isHideConfirmButton)
            {
                BtnConfirm.gameObject.SetActive(false);
            }
            if (mData.isHideCancelButton)
            {
                BtnCancel.gameObject.SetActive(false);
            }

            TextVersion.text = mData.version;
            TextTip.text = mData.message;
            BtnCancel.onClick.AddListener(()=>{
                Back();
            });
            BtnConfirm.onClick.AddListener(()=>{
                Application.OpenURL(mData.url);
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
