//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:44f8ae6a-066a-4fc4-bd90-ccee45690538
    public partial class UserInfoPanel
    {
        
        public const string NAME = "UserInfoPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform UserPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnUserMask;
        
        [SerializeField()]
        public CircleImage ImgUserHead;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnFather;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnMother;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnGrandFather;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnGrandMother;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBrother;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnSister;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnUserConfirm;
        
        [SerializeField()]
        public UnityEngine.UI.Text Text;
        
        private UserInfoPanelData mPrivateData = null;
        
        public UserInfoPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UserInfoPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            UserPanel = null;
            BtnUserMask = null;
            ImgUserHead = null;
            BtnFather = null;
            BtnMother = null;
            BtnGrandFather = null;
            BtnGrandMother = null;
            BtnBrother = null;
            BtnSister = null;
            BtnUserConfirm = null;
            Text = null;
            mData = null;
        }
    }
}
