//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKid
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:8e86c677-87da-4eb9-8073-64058e4f3b26
    public partial class WorksWallPanel
    {
        
        public const string NAME = "WorksWallPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text TextTitle;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAttendanceAdd;
        
        [SerializeField()]
        public UnityEngine.RectTransform Content;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnAttendanceInstructions;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnHistoryPhoto;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnBack;
        
        [SerializeField()]
        public UnityEngine.RectTransform NoDataConnect;
        
        private WorksWallPanelData mPrivateData = null;
        
        public WorksWallPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new WorksWallPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TextTitle = null;
            BtnAttendanceAdd = null;
            Content = null;
            BtnAttendanceInstructions = null;
            BtnHistoryPhoto = null;
            BtnBack = null;
            NoDataConnect = null;
            mData = null;
        }
    }
}
